#!/usr/bin/perl -w

require "qrpff";

until ( eof STDIN ) {
  read STDIN, $input, 2048;
  read STDIN, $key, 5;
  read STDIN, $wanted_output, 2048;
  
  $got_output = &c($input, $key);
  
  if ( $wanted_output eq $got_output ) {
    print "It works!\n";
  } else {
    print "Broken.\n";
  }
}
