#!/usr/bin/perl -w

require "qrpff";

use bytes;

$i=0;
until ( eof STDIN ) {
#  last if $i++ > 0;
  read STDIN, $input, 2048;
  read STDIN, $key, 5;
  read STDIN, $wanted_output, 2048;

  @a = map { ord } split //, $input;
  @b = reverse map { ord } split //, $key;

  &c;
 
  $got_output = join '', map { chr } @a;

  if ( $wanted_output eq $got_output ) {
      print "It works.\n";
  } else {
      print "Broken!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n";
  }
}
