#!/usr/bin/perl -w

require "qrpff.debug";

for $orbit_start ( 0 .. 255 ) {
    $orbit_location = $orbit_start;
    while ( not $hit{ $orbit_location } ) {
	push @{ $permutation{ $orbit_start } }, $orbit_location;
	$orbit_pointer{ $orbit_location } = $orbit_start;
	$hit{ $orbit_location } = 1;
	$orbit_location = tab( $orbit_location );
    }
}

for ( 0 .. 255 ) {
    next unless $permutation{ $_ };
    print join " => ", map { (unpack "H*", chr $_) . " ($_)" } @{ $permutation{ $_ } };
    print "\n";
}
